### ISSUE TITLE
Add unique hash for transfers and module transactions

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-transaction-service#1230] opened 2022-12-16 11:59 UTC
# What is needed?
Transfers don't have a unique way to be identified

# Background

# Solution
- For ERC20/ERC721 transfers, use `keccak256("transfer" + tx_hash + logIndex)`
- For Ether transfers, it's not so easy, maybe `keccak256("transfer" + tx_hash + logIndex)` for `L2` networks or `keccak256("transfer" + tx_hash + traceAddress)` for `non L2`.

# Related issues
- https://github.com/safe-global/safe-client-gateway/issues/1033

**Comment by Uxio0** [comment] 2023-02-09 12:11
@hectorgomezv @fmrsabino I understand this is still required, please push it when it's required

**Comment by hectorgomezv** [comment] 2023-02-09 14:01
Yes, this is still required to implement https://github.com/5afe/safe-client-gateway-nest/issues/262. I've linked the issue to this one and set it as blocked. Thanks! 🙂

**Comment by fmrsabino** [comment] 2023-02-09 14:38
> @hectorgomezv @fmrsabino I understand this is still needed, please push it when it's required

Yes it is still required. It affects two types of transactions (Module and Transfers).

### On the Safe Client Gateway:

Ethereum transfers are identified with: `ethereum_<safe-address>_<transaction-hash>_<details-hash>`.
Module transactions are identified with `module_<safe-address>_<transaction-hash>_<details-hash>`

The `details-hash` is a concept that exists only on the Safe Client Gateway side and it is the root cause of the issue – since we cannot use this `details-hash` to get the transfer/module tx from the Safe Transaction Service we try to get it from the first page.

`details-hash` creation on the Safe Client Gateway: https://github.com/safe-global/safe-client-gateway/blob/31459c83b4c5edeccdb0ef880717d8de5c7cd98b/src/routes/transactions/converters/transaction_id.rs#L28-L48 

So the goal is to replace the `details_hash` with one returned by the Safe Transaction Service. Maybe this implies that `<transaction-hash>_<details-hash>` can be both merged together into one unique id too.

### On the Safe Transaction Service:

It should be possible to retrieve a single transfer or a single module transaction using the new `id`.

### On the client side:

I don't believe this should affect the clients at all unless they parse the id parts in some way (this should be looked into). Therefore I also believe that new endpoints are not required on the Safe Client Gateway side since this should be only an internal change.

**Comment by Uxio0** [comment] 2023-02-09 15:39
Thanks for the input, we are prioritizing it then

**Comment by Uxio0** [comment] 2023-02-16 13:35
Hi @fmrsabino @hectorgomezv, @moisses89 has been analyzing a solution for this but it will require a major refactor:
- A DB field needs to be added for multiple tables
- Hash calculation for every transfer/module tx will slow down indexing

Our proposed solution would be calculating the hash on the fly:
- We will return a `uniqueHash` field (or similar) for every transfer/module transaction in every endpoint they are returned (we will be calculating them on the fly)
- When querying for it, we will need to get the `Safe address`, `tx hash` and the new `unique hash` (as oposed to what would be expected, passing only `unique hash`). That way we will be able to iterate the relevant transactions, generate the `unique hash` and return the relevant one if found.

**Comment by hectorgomezv** [comment] 2023-02-17 15:29
Hello @Uxio0! Thank you and @moisses89 for analyzing this issue. 

> * When querying for it, we will need to get the `Safe address`, `tx hash` and the new `unique hash` (as oposed to what would be expected, passing only `unique hash`). That way we will be able to iterate the relevant transactions, generate the `unique hash` and return the relevant one if found.

The solution you proposed makes sense to me, both the `Safe address` and the `Transaction hash` are already included in the current `id`. If I understand it correctly the Transaction Service should be able to just extract these values by parsing the `id` string. 

> * A DB field needs to be added for multiple tables
> * Hash calculation for every transfer/module tx will slow down indexing

Could it be saving the generated `uniqueHash` the first time it's generated a possible solution? This would speed up subsequent queries without slowing down indexing, but of course, it doesn't solve the new DB field problem. Just throwing it as an idea, maybe it doesn't make much sense, but you have all the context. 🙂

Out of curiosity (and maybe it's a dummy question): is it mandatory to use a double `hash` here (`txHash` and `uniqueHash`? What prevents us from just numbering the module/transfers belonging to the same transaction?

**Comment by Uxio0** [comment] 2023-02-17 15:52
> If I understand it correctly the Transaction Service should be able to just extract these values by parsing the id string.

That `id` string is not used anywhere on the transaction service, so you would need to parse it before querying the tx service, but should be easy as the other information is already there.

> Could it be saving the generated uniqueHash the first time it's generated a possible solution? This would speed up subsequent queries without slowing down indexing, but of course, it doesn't solve the new DB field problem. Just throwing it as an idea, maybe it doesn't make much sense, but you have all the context. slightly_smiling_face

That's a really good idea @hectorgomezv , we will implement that but using Redis instead of the database.

 > Out of curiosity (and maybe it's a dummy question): is it mandatory to use a double hash here (txHash and uniqueHash)? What prevents us from just numbering the module/transfers belonging to the same transaction? I mean, just composing the id with: ethereum/module_safeAddress_txHash_0, ethereum/module_safeAddress_txHash_1...

We could also return the identifier we plan to use to calculate the hash, `traceAddress` (e.g. `0,3`, `1,2,23,0`...) for ether transfers and module transactions and `logIndex` (e.g. `0`, `23`...) for ERC20/721 transfers.

**Closed** 2023-05-05 13:58 UTC
Labels: enhancement
